server:
  port: 8080

spring:
  datasource:
    url: agencia-de-autos-lorenzopachioli-42fa.a.aivencloud.com/defaultdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: avnadmin
    password:  ${MYSQL_PASS:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# CONFIGURACIÓN DE SWAGGER / OPENAPI PARA SPRING BOOT 4
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  use-management-port: false

jwt:
  secret-key: ${SECRET_KEY:4e7d8c9b1a2f3e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b1a2f3e5d6c7b8a9f0e1d}
  expiration: ${JWT_EXPIRATION:3600000}