server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agencia_de_autos_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: emiliano
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# CONFIGURACIÓN DE SWAGGER / OPENAPI PARA SPRING BOOT 4
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  use-management-port: false